indicate success/fail of last command in PS1, better color handling

diff --git a/configs/bash_prompt b/configs/bash_prompt
--- a/configs/bash_prompt
+++ b/configs/bash_prompt
@@ -3,6 +3,7 @@
 # Heavily inspired by @necolas's prompt: https://github.com/necolas/dotfiles
 # Also borrows from @infinitwarp's bash-powerline: https://github.com/infinitewarp/bash-powerline/tree/develop
 
+# Color ref: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
 # Color ref: http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim
 # More tips: http://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html
 
@@ -54,89 +55,90 @@ function set_prompts() {
         fi
     }
 
-    local black=""
-    local blue=""
-    local bold=""
-    local cyan=""
-    local green=""
-    local orange=""
-    local purple=""
-    local red=""
-    local reset=""
-    local white=""
-    local yellow=""
-
-    local hostStyle=""
-    local userStyle=""
-
     if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
         tput sgr0 # reset colors
 
-        bold=$(tput bold)
-        reset=$(tput sgr0)
+        readonly BOLD=$(tput bold)
+        readonly RESET=$(tput sgr0)
 
-        black=$(tput setaf 0)
-        blue=$(tput setaf 4)
-        cyan=$(tput setaf 6)
-        green=$(tput setaf 2)
-        light_purple=$(tput setaf 61)
-        orange=$(tput setaf 9)
-        magenta=$(tput setaf 5)
-        purple=$(tput setaf 125)
-        red=$(tput setaf 1)
-        violet=$(tput setaf 13)
-        white=$(tput setaf 15)
-        yellow=$(tput setaf 3)
+        readonly FG_BLACK=$(tput setaf 0)
+        readonly FG_RED=$(tput setaf 1)
+        readonly FG_GREEN=$(tput setaf 2)
+        readonly FG_YELLOW=$(tput setaf 3)
+        readonly FG_BLUE=$(tput setaf 4)
+        readonly FG_MAGENTA=$(tput setaf 5)
+        readonly FG_CYAN=$(tput setaf 6)
+        readonly FG_WHITE=$(tput setaf 15)
+
+        # 256-color mode
+        readonly FG_ORANGE=$(tput setaf 208)
+        readonly FG_VIOLET=$(tput setaf 201)
+        readonly FG_PURPLE=$(tput setaf 128)
     else
-        bold=""
-        reset="\e[0m"
+        readonly BOLD=""
+        readonly RESET="\e[0m"
 
-        black="\e[1;30m"
-        blue="\e[1;34m"
-        cyan="\e[1;36m"
-        green="\e[1;32m"
-        light_purple="\e[1;35m"
-        magenta="\e[1;35m"
-        orange="\e[1;33m"
-        purple="\e[1;35m"
-        red="\e[1;31m"
-        white="\e[1;37m"
-        yellow="\e[1;33m"
+        readonly FG_BLACK="\e[1;30m"
+        readonly FG_RED="\e[1;31m"
+        readonly FG_GREEN="\e[1;32m"
+        readonly FG_YELLOW="\e[1;33m"
+        readonly FG_BLUE="\e[1;34m"
+        readonly FG_MAGENTA="\e[1;35m"
+        readonly FG_CYAN="\e[1;36m"
+        readonly FG_WHITE="\e[1;37m"
+
+        # 256-color mode
+        readonly FG_ORANGE="\e[38;5;208m"
+        readonly FG_VIOLET="\e[38;5;201m"
+        readonly FG_PURPLE="\e[38;5;128m"
     fi
 
     # build the prompt
 
     # logged in as root
     if [[ "$USER" == "root" ]]; then
-        userStyle="\[$red\]"
-        shellSymbol="#"
+        readonly USER_STYLE="\[$FG_RED\]"
+        readonly SHELL_SYMBOL="#"
     else
-        userStyle="\[$orange\]"
-        shellSymbol="\$"
+        readonly USER_STYLE="\[$FG_ORANGE\]"
+        readonly SHELL_SYMBOL="\$"
     fi
 
     # connected via ssh
     if [[ "$SSH_TTY" ]]; then
-        hostStyle="\[$bold$red\]"
+        readonly HOST_STYLE="\[$BOLD$FG_RED\]"
     else
-        hostStyle="\[$yellow\]"
+        readonly HOST_STYLE="\[$FG_YELLOW\]"
     fi
 
-    # set the terminal title to the current working directory
-    PS1="\[\033]0;\w\007\]"
+    function setP1P2() {
+        # Check the exit code of the previous command and display different
+        # colors in the prompt accordingly.
+        if [ $? -eq 0 ]; then
+            local STATUS_SHELL="\[$FG_WHITE\]${SHELL_SYMBOL}"
+        else
+            local STATUS_SHELL="\[$FG_RED\]!"
+        fi
 
-    PS1+="\n\[${bold}\]" # newline and embolden everything to come
-    PS1+="\[$userStyle\]\u" # username
-    PS1+="\[$white\]@"
-    PS1+="\[$hostStyle\]\h" # host
-    PS1+="\[$white\]: "
-    PS1+="\[$green\]\w" # working directory
-    PS1+="\$(prompt_git \"$white on $cyan\")" # git repository details
-    PS1+="\$(prompt_virtualenv \"$white using $magenta\")" # python virtualenv details
-    PS1+="\n"
-    PS1+="\[$white\]$shellSymbol \[$reset\]" # $ (and reset color)
+        # set the terminal title to the current working directory
+        PS1="\[\033]0;\w\007\]"
 
-    PS2="\[${yellow}\]→ \[${reset}\]"
+        PS1+="\n\[${BOLD}\]" # newline and embolden everything to come
+        PS1+="\[${USER_STYLE}\]\u" # username
+        PS1+="\[${FG_WHITE}\]@"
+        PS1+="\[${HOST_STYLE}\]\h" # host
+        PS1+="\[${FG_WHITE}\]: "
+        PS1+="\[${FG_GREEN}\]\w" # working directory
+        PS1+="\$(prompt_git \"${FG_WHITE} on ${FG_CYAN}\")" # git repository details
+        PS1+="\$(prompt_virtualenv \"${FG_WHITE} using ${FG_MAGENTA}\")" # python virtualenv details
+        PS1+="\n"
+        PS1+="${STATUS_SHELL} \[$RESET\]" # $ (and reset color)
+
+        PS2="\[${YELLOW}\]→ \[${RESET}\]"
+    }
+
+    PROMPT_COMMAND=setP1P2
 }
 
-PROMPT_COMMAND=set_prompts
+set_prompts
+unset set_prompts
